name: Run Tests on Push or Pull Request to Main

on:
  push:
    branches:
      - main  # Run tests on any push to the main branch
  pull_request:
    branches:
      - main  # Run tests on any pull request to the main branch

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies from requirements.txt
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-cov  # Ensure pytest-cov is installed

      - name: Run tests with pytest
        run: |
          pytest --cov=app

      - name: Log in to DockerHub (optional, if pushing)
        if: github.event_name == 'push'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -t test_qr_codemaker:latest .

      # Optional: Push to DockerHub (only on main push)
      - name: Push Docker image
        if: github.event_name == 'push'
        run: |
          docker tag test_qr_codemaker:latest jeffches15/test_qr_codemaker:latest
          docker push jeffches15/test_qr_codemaker:latest
